### ISSUE TITLE
MetaChip only identifies one gene in test dataset

### ISSUE THREAD

**Issue by Cables4lyfe** [songweizhi/MetaCHIP#11]
Hello

When I run MetaCHIP with the provided test dataset it only seems to identify a single gene (see attached output).
[Test_pcofg_detected_HGTs.txt](https://github.com/songweizhi/MetaCHIP/files/5429169/Test_pcofg_detected_HGTs.txt)
[Test_HGTs_among_classes.pdf](https://github.com/songweizhi/MetaCHIP/files/5429172/Test_HGTs_among_classes.pdf)

Do you have any idea, what might have went wrong?

Thanks!

**Comment by songweizhi** [comment]
Hi, it's all good to got only one gene transfer (from bin829 to bin30) as it's a very small dataset. the main purpose of this dataset is to show users how the input files look like.
