### ISSUE TITLE
Error thrown while running BP

### ISSUE THREAD

**Issue by shreyanshumale** [songweizhi/MetaCHIP#12]
Error in the terminal: 

Command line argument error: Argument "subject". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Myxococcales_bacterium_UW$
Command line argument error: Argument "subject". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Myxococcales_bacterium_UW$
Command line argument error: Argument "query". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Candidatus_Marinimicrobia_b$
Command line argument error: Argument "query". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Candidatus_Marinimicrobia_b$
Command line argument error: Argument "subject". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Planctomycetes_bacterium_$
Command line argument error: Argument "subject". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Planctomycetes_bacterium_$
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/lib/python3.6/site-packages/MetaCHIP/BP.py", line 861, in get_gbk_blast_act2
    for blast_hit in open(output_c_full_len):
FileNotFoundError: [Errno 2] No such file or directory: 'northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Alphaproteobacteria_bacterium_UWMA-0321_017$
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/bin/MetaCHIP", line 168, in <module>
    BP(args, config_dict)
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/lib/python3.6/site-packages/MetaCHIP/BP.py", line 2164, in BP
    pool_flanking_regions.map(get_gbk_blast_act2, list_for_multiple_arguments_flanking_regions)
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/shreyansh/anaconda3/envs/MetaCHIP/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Alphaproteobacteria_bacterium_UWMA-0321_017$

Please let know where am I going wrong!

**Comment by songweizhi** [comment]
Hi,
did the name of your genomes contain "$", can you please try again after removing these symbols from your mag name?

**Comment by shreyanshumale** [comment]
I am sorry for the confusion, I copy pasted the error from a file opened in nano, So $ just represents more letters in the line and is not part of any file or filename.
Sample error line: Command line argument error: Argument "subject". File is not accessible:  `northsea_MetaCHIP_wd/northsea_HGT_ip90_al200bp_c75_ei80_f10kbp_p18/northsea_p18_Flanking_region_plots/Alphaproteobacteria_bacterium_UWMA-0321_01783___Candidatus_Pacearchaeota_archaeon_UWMA-0287_00284.
/Candidatus_Pacearchaeota_archaeon_UWMA-0287_00284_10000bp.fasta'

I get the same error for a bunch of other genomes too. Although the flanking region plots are generated for some of the pairs.

**Comment by songweizhi** [comment]
I tried to run MetaCHIP on several datasets, however, I failed to reproduce the error you encountered. Can you please share with me some of your input files and the commands?

**Comment by shreyanshumale** [comment]
Hello!
I just mailed them to you. Please let me know if I can help in any other way!

**Comment by songweizhi** [comment]
Hi, 

It turns out that MetaCHIP failed to generate the blast database for your dataset, and here is the error message I got: "BLAST Database creation error: Near line 56351, the local id is too long.  Its length is 55 but the maximum allowed local id length is 50.  Please find and correct all local ids that are too long."

This is due to some long names of your input genomes, as MetaCHIP uses genome name (without extension) as prefix to the id of its coded genes.

can you please shorten the name of your input genomes and try again?

**Comment by shreyanshumale** [comment]
Hello Dr. Song,

Thanks a lot for your help! I think the program runs till the HGT detection
step after shortening the filenames. Although, now I encounter this error
repeatedly:

"major.tick.percentage` is not used any more, please directly use argument
`major.tick.length`."

Can you please help me with how to resolve this?

Thanks
Shreyansh

**Comment by songweizhi** [comment]
Hi,

This is due to a recent update of the R package Circos. This alert won't affect HGT detection, but might affects the layout of elements on the plot which shows gene flow among taxons.
It has been fixed, please update MetaCHIP to the latest version(1.10.2) with "pip install --upgrade MetaCHIP".

Cheers,
Weizhi
