### ISSUE TITLE
Question about average group identity

### ISSUE THREAD

**Issue by arsuke** [songweizhi/MetaCHIP#15]
Hi.
Thank you for developing great tools.
I have a question for searching gene candidate for HGT using average group identity.

I understand a gene is considered as a candidate for HGT when it has the highest similarity with other group.
However, some genes have highest similarity to self group while they are also very similar to other groups. In this case, are those genes not considered as gene candidate for HGT?

Thank you!

**Comment by songweizhi** [comment]
Hi, 
In this case, the gene won't be considered as a HGT as the highest similarity was found within its own group.
