### ISSUE TITLE
what is blastdb/*.fasta ?

### ISSUE THREAD

**Issue by mmpust** [songweizhi/MetaCHIP#16]
Hello,

what is the file called *_combined_ffn.fasta in the directory *_cofg_blastdb/ after running metaCHIP? 
The file can be accessed as follows

```
cd test_MetaCHIP_wd/
ls -1
test_cofg_blastdb/
test_cofg_blastn_commands.txt
test_cofg_blastn_results/
test_cofg_blastn_results_filtered_al200bp_cov75/
test_cofg_combined_faa.fasta
test_cofg_get_SCG_tree_wd/
test_cofg_log_files/
test_cofg_prodigal_output/
test_cofg_SCG_tree_cov50_css25.aln
test_cofg_SCG_tree.newick
test_combined_cofg_HGTs_ip90_al200bp_c75_ei80_f10kbp/
test_grouping_c9.txt
test_grouping_f26.txt
test_grouping_g43.txt
test_grouping_o15.txt
test_HGT_ip90_al200bp_c75_ei80_f10kbp_c9/
test_HGT_ip90_al200bp_c75_ei80_f10kbp_f26/
test_HGT_ip90_al200bp_c75_ei80_f10kbp_g43/
test_HGT_ip90_al200bp_c75_ei80_f10kbp_o15/

cd test_cofg_blastdb/
ls -1
test_cofg_combined_ffn.fasta
test_cofg_combined_ffn.fasta.nhr
test_cofg_combined_ffn.fasta.nin
test_cofg_combined_ffn.fasta.nog
test_cofg_combined_ffn.fasta.nsd
test_cofg_combined_ffn.fasta.nsi
test_cofg_combined_ffn.fasta.nsq
```

Thank you very much!
Marie

**Comment by songweizhi** [comment]
Hi Marie,
These files are used for performing all-against-all BLAST among genes predicted from all input genomes. 
Weizhi

**Comment by mmpust** [comment]
Hey Weizhi,
thank you very much indeed for this fast response. 

So, the FASTA file in this particular directory contains all protein-coding sequences from all input genomes called with prodigal? But this has nothing to do with the predicted HGT genes? Is that correct? Thanks!

Cheers,
Marie

**Comment by songweizhi** [comment]
Yes, you're right, they are the protein-coding sequences from all input genomes called with prodigal.
These files are generated in the PI step, and only the blast results are used for HGT detection in the best-match approach.
Cheers,
Weizhi

**Comment by mmpust** [comment]
Great! Many thanks for the immediate support.
