### ISSUE TITLE
Error in PI step

### ISSUE THREAD

**Issue by BJCampbelllab** [songweizhi/MetaCHIP#19]
Hi-
I installed MetaCHIP through an ete3 conda environment.  I get the general command list when I type MetaCHIP.  I ran the summarize command on a bunch of gbf files and that worked.  However, when I went to do the PI command with the test sequences (NorthSea bins), it gives me this error:

(ete3) [bcampbell@localhost Metachip]$ MetaCHIP PI -p Metachip_test -g Test_metachip.txt -t 20 -i /home/shared/MetaCHIP_test/Metachip -x fasta
[2021-04-19 16:03:13] Total number of qualified genomes for HGT detection: 4.[2021-04-19 16:03:13] Running Prodigal for 4 qualified genomes with 20 cores (1-3 minutes pre genome per core).
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/site-packages/MetaCHIP/PI.py", line 233, in prodigal_worker    prodigal_parser(pwd_input_genome, pwd_output_sco, input_genome_basename, pwd_prodigal_output_folder)  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/site-packages/MetaCHIP/PI.py", line 202, in prodigal_parser
    SeqIO.write(current_SeqRecord, bin_gbk_file_handle, 'genbank')  File "/home/bcampbell/.local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 533, in write
    count = writer_class(fp).write_file(sequences)  File "/home/bcampbell/.local/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 237, in write_file
    count = self.write_records(records)  File "/home/bcampbell/.local/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 222, in write_records
    self.write_record(record)  File "/home/bcampbell/.local/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 830, in write_record
    self._write_the_first_line(record)  File "/home/bcampbell/.local/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 631, in _write_the_first_line
    raise ValueError("Need a Nucleotide or Protein alphabet")
ValueError: Need a Nucleotide or Protein alphabet
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bcampbell/anaconda3/envs/ete3/bin/MetaCHIP", line 165, in <module>
    PI(args, MetaCHIP_config.config_dict)  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/site-packages/MetaCHIP/PI.py", line 870, in PI
    pool.map(prodigal_worker, list_for_multiple_arguments_Prodigal)  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()  File "/home/bcampbell/anaconda3/envs/ete3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: Need a Nucleotide or Protein alphabet

It's not putting data into the genbank files, but other files were generated before that step.  I checked biopython (installed in the conda environment), but it said the requirement was already satisfied.

I am the administrator of the workstation.  Another user installed biopython outside the conda environment (I think) and MetaCHIP is working.  

Any suggestions?  We had problems with FastTree as well, but put that in the path for everyone to use. 

Thanks!
Barb

**Comment by songweizhi** [comment]
hi，
Can you please update bio python to the latest version and try again.
Cheers,
Weizhi

**Comment by hickman-santini** [comment]
I had the same problem and upgrading biopython (to 1.78) worked for me. Thanks @songweizhi

**Comment by nick-youngblut** [comment]
It appears that the [metachip bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/metachip/meta.yaml) is still set to use `biopython <=1.77`

Recipe maintainer: https://github.com/apcamargo

**Comment by nick-youngblut** [comment]
Now I can see why:

```
Looking for: ["biopython[version='>=1.78']"]

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
bioconda/linux-64        Using cache
bioconda/noarch          Using cache
pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache
r/linux-64               Using cache
r/noarch                 Using cache
leylabmpi/noarch         [====================] (00m:00s) No change
qiime2/linux-64          [====================] (00m:00s) No change
leylabmpi/linux-64       [====================] (00m:00s) No change
qiime2/noarch            [====================] (00m:00s) No change
Encountered problems while solving:
  - package metachip-1.10.5-pyh5e36f6f_0 requires biopython <=1.77, but none of the providers can be installed
```

Some dependency of MetaCHIP conflicts with `biopython>=1.78`
