### ISSUE TITLE
Unknown Classification

### ISSUE THREAD

**Issue by susheelbhanu** [songweizhi/MetaCHIP#2]
Hi, 

Thanks for a nice tool. I tried it on some of my bins, and found a classification as follows:
```B12.metabat.65.contigs_02841    B12.metabat.77.contigs_02542    G       A       81.394  no      no      B12.metabat.65.contigs-->B12.metabat.77.contigs```

However, I am not sure what the "G" stands for in this. Could you please let me know?

I also found in another sample "H" and "G".
```B12.metabat.65.contigs_02841    B12.metabat.77.contigs_02542    H       A       81.394  no      no      B12.metabat.65.contigs-->B12.metabat.77.contigs
B12.metabat.65.contigs_01463    B12.metabat.40.contigs_00582    H       G       85.023  no      no```

Thanks for your help!

**Comment by susheelbhanu** [comment]
I think I may figured this out, but could you please confirm. In the grouping file, the bins are assigned to specific groups, which range from A through H. 

Could you please confirm if the above classification references these groups?

Thank you!

**Comment by songweizhi** [comment]
Hi Susheel, 
yes,  it refers to the index of the bin groups in the grouping file.
