### ISSUE TITLE
linclust as alternative to all-vs-all blastn

### ISSUE THREAD

**Issue by nick-youngblut** [songweizhi/MetaCHIP#20]
Given that lack of scalability for all-vs-all blastn, it would be great to have the option to use `mmseqs linclust` as an alternative

**Comment by clb21565** [comment]
agreed. In addition, a tool like minimap2 could be used effectively at a fraction of the time. At least, it could create a subset for more careful alignment

**Comment by songweizhi** [comment]
Thanks for your suggestion, I am currently preparing a major update to MetaCHIP, `mmseqs linclust` will be incorporated in this version to speed up all-vs-all blast.
