### ISSUE TITLE
Problem Running BP 

### ISSUE THREAD

**Issue by nevermind1996** [songweizhi/MetaCHIP#21]
Hello Dr. Song, I run the following command under the folder  MetaCHIP/input_file_examples/human_gut_bins/, and the error below showed up. Could you help me with this? Thank you. Zirui

MetaCHIP BP -p GUT_BP -g /work/cascades/zirui/MetaChIP/customized_grouping.txt  -t 6

Traceback (most recent call last):
  File "/home/zirui/miniconda3/bin/MetaCHIP", line 168, in <module>
    BP(args, MetaCHIP_config.config_dict)
  File "/home/zirui/miniconda3/lib/python3.8/site-packages/MetaCHIP/BP.py", line 1732, in BP
    pwd_prodigal_output_folder_detected    = [os.path.basename(file_name) for file_name in glob.glob(pwd_prodigal_o                                        utput_folder_re)][0]
IndexError: list index out of range

**Comment by susheelbhanu** [comment]
similar to #26
