### ISSUE TITLE
Singularity use

### ISSUE THREAD

**Issue by Lcornet** [songweizhi/MetaCHIP#22]
Hello,

I installed Metachip in a singularity container, it works well but I am not able to write output:

Detect HGT among phyla: Best-match approach.
[2021-07-28 13:48:28] Detect HGT among phyla: get group-to-group identities with 20 cores.
sort: cannot create temporary file in '/tmpscratch/lcornet/1278701': No such file or directory

It is because singularity on HPC cluster don't allow writing in the current directory. It must been launch with a command like : 
 singularity exec --bind /scratch/ulg/bioec/lcornet/Metachip:/mnt MetaCHIP.img MetaCHIP

So everything is written in /mnt and not in /tmpscratch/lcornet/. Is it possible to add a output directory in an option ?

Best regards,
Luc

**Comment by songweizhi** [comment]
Hi, you can designate a place for the output files with "-o" now (v1.10.6).
