### ISSUE TITLE
Error in PI step with Prodigal

### ISSUE THREAD

**Issue by ddf37** [songweizhi/MetaCHIP#27]
Hi,

We're running into an issue during the PI step with Prodigal. We get the following message back:

[2021-11-19 11:31:33] Total number of qualified genomes for HGT detection: 98.
[2021-11-19 11:31:33] Running Prodigal for 98 qualified genomes with 1 cores (1-3 minutes per genome per core).
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages/MetaCHIP/PI.py", line 238, in prodigal_worker
    prodigal_parser(pwd_input_genome, pwd_output_sco, input_genome_basename, pwd_prodigal_output_folder)
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages/MetaCHIP/PI.py", line 138, in prodigal_parser
    transl_table = seq_to_transl_table_dict[seq_id]
KeyError: 'CVPL010W_10000976'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ddf37/.conda/envs/metachip/bin/MetaCHIP", line 166, in <module>
    PI(args, MetaCHIP_config.config_dict)
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages/MetaCHIP/PI.py", line 879, in PI
    pool.map(prodigal_worker, list_for_multiple_arguments_Prodigal)
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ddf37/.conda/envs/metachip/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'CVPL010W_10000976'

The code that was use is as follows:

MetaCHIP PI -p Demo1_1Node -g /ifs/groups/russellGrp/ddf37/metachippkg/Genometax.txt -t 1 -i /ifs/groups/russellGrp/ddf37/metachippkg/genomes -x fasta

We have checked to make sure the program and dependencies are up to date:

Requirement already satisfied: MetaCHIP in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (1.10.8)
Requirement already satisfied: scipy in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from MetaCHIP) (1.7.2)
Requirement already satisfied: biopython in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from MetaCHIP) (1.79)
Requirement already satisfied: ete3 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from MetaCHIP) (3.1.2)
Requirement already satisfied: matplotlib in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from MetaCHIP) (3.5.0)
Requirement already satisfied: numpy in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from MetaCHIP) (1.21.4)
Requirement already satisfied: reportlab in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from MetaCHIP) (3.6.2)
Requirement already satisfied: cycler>=0.10 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (21.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (4.28.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (1.3.2)
Requirement already satisfied: setuptools-scm>=4 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (6.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from matplotlib->MetaCHIP) (2.4.7)
Requirement already satisfied: six>=1.5 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->MetaCHIP) (1.16.0)
Requirement already satisfied: setuptools in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from setuptools-scm>=4->matplotlib->MetaCHIP) (59.1.1)
Requirement already satisfied: tomli>=1.0.0 in /home/ddf37/.conda/envs/metachip/lib/python3.10/site-packages (from setuptools-scm>=4->matplotlib->MetaCHIP) (1.2.2)

This was all done on a computing cluster. Any help would be appreciated!

**Comment by songweizhi** [comment]
could you please share with me the MAG that contains contig CVPL010W_10000976, as well as the corresponding sco file which can be found in the prodigal output folder? your file will only be used for debugging purpose.
Weizhi

**Comment by ddf37** [comment]
Hi Weizhi,

Attached are the MAG and sco file for containing contig CVPL010W_10000976.

Thank you,
Daniel

________________________________

**Comment by songweizhi** [comment]
please update MetaCHIP to version 1.10.9 and see if you can bypass this error
Weizhi

**Comment by ddf37** [comment]
That seemed to work. Thank you for your help!

Daniel

________________________________
