### ISSUE TITLE
Is there a way to suppress generation of flanking region plots?

### ISSUE THREAD

**Issue by polinanvkv** [songweizhi/MetaCHIP#37]
Hello,

I am running metaCHIP on 1k archaeal genomes, and I am running out of file quota due to flanking region plots (in `genomes_s6_Flanking_region_plots`). Is there a way to suppress generation of these plots as at the end of the story the only plot I am interested in is the circos plot? 

Thank you!

**Comment by songweizhi** [comment]
The plot of flanking regions of identified HGTs is disabled by default (>=1.10.10),  you can provide "-pfr" to the BP module to get the plot.
