### ISSUE TITLE
No alias or index file found for nucleotide database

### ISSUE THREAD

**Issue by schmittel** [songweizhi/MetaCHIP#38]
As reported by others previously, I am getting the following error during the PI step:

```
BLAST Database error: No alias or index file found for nucleotide database [/metachip/gut/output/gut_pcofg_blastdb/gut_pcofg_combined_ffn.fasta] in search path [/databases/gut/renamed::]
```

Here's my code:

```
MetaCHIP PI -i /databases/gut/renamed -o /metachip/gut/output -p gut -r pcofg -x fna -taxon taxonomy.txt -force -t 32
```

Unlike those with this issue previously, it doesn't seem to be due to the length of the filenames. All filenames and fasta headers are less than 20 characters. It seems that the `gut_pcofg_combined_ffn.fasta` file for making the BLAST database is not being generated as its size is zero. 

Your help is appreciated, thanks.

**Comment by songweizhi** [comment]
Hi Schmittel,
Thank you for reporting the issue, I never succeed in reproducing this error on my side, can you please share with me your inputs to MetaCHIP so I can take a look at this issue? your files will only be used for debugging.
Best,
Weizhi
