### ISSUE TITLE
All files in strain_pcofg_blastn_results are empty, program exited

### ISSUE THREAD

**Issue by weiting-liang** [songweizhi/MetaCHIP#39]
hi, song!
I'm sorry to bother you. but I got some error, when I run MetaCHIP BP: "All files in strain_pcofg_blastn_results are empty, program exited." 
PI have done and the "strain_pcofg_blastn_results" directory is not empty, which have many files, such as GCF_900117335.1_PRJEB17656_genomic_blastn.tab, ... ...

what should i do?

**Comment by songweizhi** [comment]
Hi Weiting,

According to the error report, all files in strain_pcofg_blastn_results are empty, is this the case?
Do you have the blast+ program properly installed? Did you see any errors when running makeblastdb?

Best,
Weizhi

**Comment by weiting-liang** [comment]
Yes, I have blast+ and I have run your demo. It could be completely done.
I found nohup.txt which display this : "BLAST Database creation error: Near line 1757661, the local id is too long.  Its length is 52 but the maximum allowed local id length is 50.  Please find and correct all local ids that are too long."
Is that the problem?
I try to solve it. Thank you!

Best,
Weiting

**Comment by songweizhi** [comment]
It's likely due to the long id of contigs in some of your genomes, maybe you could try to shorten them and try again.
Weizhi
