### ISSUE TITLE
Biopython need to be >= 1.78, MetaCHIP exited!

### ISSUE THREAD

**Issue by B-1991-ing** [songweizhi/MetaCHIP#44]
Hi weizhi,

I already installed the MetaCHIP under my own directory through the conda installation. But, when running, error happened.

**Conda installation**
module load tools #pre for miniconda3/4.14.0
module load miniconda3/4.14.0
module load intel/perflibs/64/2020_update2 
module load gcc/7.4.0
module load R/4.2.0
conda create -n MetaCHIP
conda activate MetaCHIP
conda install -c conda-forge -c bioconda MetaCHIP
conda deactivate

**Running command lines**
module load tools #pre for miniconda3/4.12.0
module load miniconda3/4.12.0
module load intel/perflibs/64/2020_update2 
module load gcc/7.4.0
module load R/4.2.0
conda activate MetaCHIP 
MetaCHIP PI -p HGT_sib -r s -t 20 -i ${in_dir} -x fasta -taxon ${MAG_GTDB}
MetaCHIP BP -p HGT_sib -r s -t 20
conda deactivate 

**Error**
<img width="1343" alt="Screenshot 2023-04-05 at 19 58 04" src="https://user-images.githubusercontent.com/54441633/230164284-1e574ef2-2cb8-44f7-a847-8c59f8ffac4d.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
Update

conda activate MetaCHIP

#update biopython to 2.17
conda update biopython

conda deactivate

**Comment by B-1991-ing** [comment]
Update

Finally, I used the MetaCHIP 1.10.12 installed by the HPC administer.

**Comment by nagoue** [comment]
Hi @B-1991-ing , 
May you give more info on the install on a HPC please ?
I tried both install of MetaCHIP with conda or mamba with version 1.10.12 and 1.10.13 but still I have issue with biopython:
`Biopython need to be >= 1.78, MetaCHIP exited!`
Thanks !

**Comment by songweizhi** [comment]
can you please activate you conda environment and see if "pip install biopython==1.81" helps?

**Comment by nagoue** [comment]
Great, it did the job. Thanks a lot ! :+1:
