### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by pancrystal** [songweizhi/MetaCHIP#48]
Hi,

I recently downloaded MetaCHIP and have installed the dependencies on the same directory, and when I list them, they show, but I cannot run the code without error saying some third party dependencies are missing. Has anyone gone through similar issues or is there a guide to see how to diagnose this?

[Terminal Saved Output.txt](https://github.com/songweizhi/MetaCHIP/files/11445737/Terminal.Saved.Output.txt)

**Comment by joynerco22** [comment]
Hi there,
Did you install the dependencies using a package manager like Pip? It could be an issue of where the program isn't finding the executables on your systems file path. I would try modifying the MetaCHIP_config.py script and provide the paths to the dependencies' executables on your system and see if that works. It should be in the directory lib/site-packages/MetaCHIP.

**Comment by pancrystal** [comment]
Hi, I installed the python libraries via pip3 and then installed the third party dependencies via brew or manually. Thanks for your response, I'll try this and then let you know!
