### ISSUE TITLE
Number of input file for metagenomic studies. ERROR: MetaCHIP working directory detected, program exited!

### ISSUE THREAD

**Issue by bahiyahazli** [songweizhi/MetaCHIP#49]
Hello, I have encountered an error. 
This is the script

`MetaCHIP PI -p ~/ky/kw1/output/hgt/freshwater_ky -r pcofgs -t 8 -o ~/ky/kw1/output/hgt/freshwater_ky -i ~/ky/kw1/output/orf -x fasta -taxon ~/ky/kw1/output/hgt/karyern_fw_hgt_taxon.tsv`

and the output was just a simple

`MetaCHIP working directory detected, program exited!
`

I am currently trying to find HGT in a metagenomic fasta sample. All the identified sequences with taxon classifications are inside 1 fasta file. None of the manual talks about if it is necessary to have more than 1 fasta/fa file in order to run MetaCHIP (hence why I'm trying my luck to use this). So, do your perhaps know if the error I got was because of the fact Im using only 1 fasta file, or it's due to other issues? 

I want to exclude MetaCHIP installation program because provided test sequence works for me. 

Thank you so much!

**Comment by bahiyahazli** [comment]
Hello, people.

I'm back with w answers.

So, about the working directory. You just have to `rm -r <output dir> --force` to remove the output directory and then, you can rerun it. I don't think there's a --continue option that allows the program to continue running where it crashes.

And about the 1 fasta file, I recommend separating the 1 fasta file with multiple sequences into individual fasta sequences.

Use this script
`cat fw_nt_KY_forhgt.fasta | awk '{
        if (substr($0, 1, 1)==">") {filename=(substr($1,2) ".fasta")}
        print $0 >> filename
        close(filename)
}'`

Thanks!

**Comment by songweizhi** [comment]
I am not sure about what do you mean by saying "1 fasta file", are you referring to a file that contains a single sequence? The input file to MetaCHIP are the sequence files of a set of genomes or MAGs, and it's ok to have multiple sequences in the genome files (actually, this might be the most common cases).
