### ISSUE TITLE
Missing ')' in input tree expression

### ISSUE THREAD

**Issue by Thexiyang** [songweizhi/MetaCHIP#5]
Thanks for the nice tool! During the running procedure of  `MetaCHIP BP`, I came across quite some error messages reading: `ERROR: missing ')' in input tree expression line x column y`. The  `MetaCHIP PI` module run well.  Is it normal? Should I trust the final output? Thanks!

**Comment by susheelbhanu** [comment]
@songweizhi: I have a similar issue as well.

**Comment by songweizhi** [comment]
The error occurred because short branch lengths in the newick tree file were indicated like “5e-09”, and Ranger reports error whenever it sees a hyphen (“-”). This bug has been fixed, please update MetaCHIP to the latest version (>1.9.1).

**Comment by susheelbhanu** [comment]
I can confirm that MetaCHIP `v.1.9.1` solves this error.
Thanks a lot for the immediate help @songweizhi!!
