### ISSUE TITLE
Error in BP module

### ISSUE THREAD

**Issue by meganzhang657** [songweizhi/MetaCHIP#9]
I got an error when I use the BP module as follow:
![image](https://user-images.githubusercontent.com/53167960/88250836-61446d80-ccdb-11ea-9da4-647a0db17083.png)
and I tried to comment out the line 1991 of BP.py but it is still not work.
Could you please help me with this.

**Comment by songweizhi** [comment]
Hi,
sorry for the error, I have fixed it, could you please update MetaCHIP with "pip install --upgrade MetaCHIP
" and try again?
Weizhi

**Comment by meganzhang657** [comment]
> Hi,
> sorry for the error, I have fixed it, could you please update MetaCHIP with "pip install --upgrade MetaCHIP
> " and try again?
> Weizhi

**Comment by meganzhang657** [comment]
Yeah ! It works now. Thank  you very much!!!
